### PR TITLE
Various DROID fixes and improvements

### LINKED ISSUE #41: Override project image with branch-specific image when a Dockerfile is present
*Currently*, at startup, the server will look in `config.edn` for the image to use with a given project and will either try to build it or pull it. If there happens to also be a Dockerfile on the master branch (or on some other branch if there is no master), then DROID will build, otherwise it will pull.

*We need to change this* to the following instead: At startup, DROID will look in `config.edn` and _pull_ all of the per-project images. If, in addition, any of the branches in the project contain a Dockerfile, then we should build an image to be used by that branch and that branch alone based on the Dockerfile.

In other words, the per-project images are to be thought of as default images. A Dockerfile on a branch will override this default image for that particular branch.

Note that in addition to performing this check at startup, we will also need to do it whenever a new branch is created or checked out.

### LINKED ISSUE #43: Add git reset --hard button
O agree with the first request in #42 that we should add a button that can reset changes to the branch.

The problem is that there's more than one reasonable behaviour. My current preference is `git reset --hard`, which I often use to clean a branch so I can pull. But there may be better ideas.

- use a red "Reset" button: "Reset this branch to the last commit"
- I think it make sense to place it after "pull" (at the bottom)
- since this is destructive, there should be a confirmation: "Reset will delete all changes since the last commit. This cannot be undone. Are you sure?": "Cancel" "Reset branch"

If we decide that there's more than one behaviour that we want to support, maybe the confirmation step can offer more options.

### LINKED ISSUE #47: Support :env map in project config, and use it for tasks including CGI
In `config.edn` under `:docker-config` there's an `:env` map that gets passed to Docker. I'd like a similar (optional) `:env` for projects, which will allow us to pass environment variables to all the tasks and CGI scripts run under any branch of the project.

This should cover the simple case discussed in #45.

### LINKED ISSUE #59: Status line on branch page should link to PR (if one exists)
@jamesaoverton had another idea, but I forgot it again in the heat of the moment. Right now the PR opens in the DROID tab which is not desirable.

### PR DESCRIPTION
**Pull request by lmcmicu**
closes #59 
closes #43 
closes #41 
closes #47

### CODE REVIEW

File: src/droid/html.clj [hunk 1]
```diff
@@ -508,104 +514,123 @@
...
 (defn render-index
   "Render the index page"
   [{:keys [params]
-    {:keys [just-logged-out rebuild-containers rebuild-launched reset really-reset]} :params,
+    {:keys [just-logged-out rebuild-images really-rebuild rebuild-launched
+            reset really-reset]} :params,
     {{:keys [login]} :user} :session,
     :as request}]
   (log/debug "Processing request in index with params:" params)
-  (letfn [(site-admin? []
```
Comment (lmcmicu) [inline src/droid/html.clj:495]: Best to ignore leading whitespace to see the changes here more clearly
